title: Variabelen en constanten toewijzen
hero_image: images/banner.png
description: Variabelen en constanten toewijzen in JavaScript
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Variabelen en constanten toewijzen
