title: Attribuer des variables et des constantes
hero_image: images/banner.png
description: Attribue des variables et des constantes en JavaScript
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Attribuer des variables et des constantes
